name: HobbyProjects

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Publish App
        run: dotnet publish --configuration Release --output build --nologo
      
      - name: Change base-tag in index.html from / to HobbyProjects
        run: sed -i 's/<base href="\/" \/>/<base href="\/HobbyProjects\/" \/>/g' build/wwwroot/index.html
        
      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: build/wwwroot
          single_commit: true

